-- Enable UUID generation extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE (Isolates multi-tenant data safely)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    is_global BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. CHARACTER VAULT TABLE (Stores reusable heroes, sidekicks, and villains)
CREATE TABLE IF NOT EXISTS character_vault (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    character_name VARCHAR(100) NOT NULL,
    role_type VARCHAR(50) NOT NULL, -- 'Hero', 'Co-Star', 'Villain'
    description TEXT,
    image_url TEXT,                 -- Secure path pointing to Google Cloud Storage or base64 data URL
    spatial_vectors JSONB,          -- For structural Gemini reference prompts
    generation_prompt TEXT,         -- Detailed prompt for generation stability
    reference_images JSONB,         -- Array of base64 strings or URLs for compatibility
    is_global BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. PROJECTS TABLE (Tracks books/comics generated by creators)
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    language VARCHAR(50) NOT NULL,
    current_page INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. PROJECT CASTING JUNCTION (Links vault characters into specific book issues)
CREATE TABLE IF NOT EXISTS project_casting (
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    character_id UUID REFERENCES character_vault(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, character_id)
);

-- Create performance indexes for rapid fetching
CREATE INDEX IF NOT EXISTS idx_character_vault_user ON character_vault(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);

-- 5. SUBSCRIPTIONS TABLE (Handles SaaS Tiers & Usage Limits)
CREATE TABLE IF NOT EXISTS subscriptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tier VARCHAR(50) DEFAULT 'Free', -- 'Free', 'Pro', 'Enterprise'
    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255),
    token_balance INT DEFAULT 500,
    renewal_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. CONTENT CATEGORIES (Global Taxonomy managed by Admins)
CREATE TABLE IF NOT EXISTS content_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_type VARCHAR(50) NOT NULL, -- 'Genre', 'Style', 'Tag'
    name VARCHAR(100) NOT NULL,
    description TEXT,
    emoji VARCHAR(10),
    prompt_instruction TEXT,
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. PUBLISHED WORKS (Community Gallery / Feed)
CREATE TABLE IF NOT EXISTS published_works (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    synopsis TEXT,
    cover_image_url TEXT,
    language VARCHAR(50) DEFAULT 'en',
    region VARCHAR(50) DEFAULT 'global',
    upvotes INT DEFAULT 0,
    views INT DEFAULT 0,
    is_featured BOOLEAN DEFAULT false,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. MODERATION FLAGS (Content safety and regional compliance queue)
CREATE TABLE IF NOT EXISTS moderation_flags (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    target_type VARCHAR(50) NOT NULL, -- 'published_work', 'character_vault'
    target_id UUID NOT NULL,
    flagged_by UUID REFERENCES users(id) ON DELETE SET NULL, -- Null if automated LLM flag
    reason TEXT NOT NULL,
    severity VARCHAR(50) DEFAULT 'medium', -- 'low', 'medium', 'high', 'critical'
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'resolved_safe', 'resolved_removed'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_published_works_region ON published_works(region);
CREATE INDEX IF NOT EXISTS idx_published_works_language ON published_works(language);
CREATE INDEX IF NOT EXISTS idx_moderation_flags_status ON moderation_flags(status);

-- Settings and Integrations Table
CREATE TABLE IF NOT EXISTS app_settings (
    key_name VARCHAR(100) PRIMARY KEY,
    key_value TEXT NOT NULL,
    is_secret BOOLEAN DEFAULT false,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Dynamic Subscription Plans Table
CREATE TABLE IF NOT EXISTS subscription_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    billing_cycle VARCHAR(50) DEFAULT 'monthly',
    features JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. WEBHOOK LOGS (System health and external events)
CREATE TABLE IF NOT EXISTS webhook_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    provider VARCHAR(50) NOT NULL,
    event_type VARCHAR(100),
    payload JSONB,
    status VARCHAR(50),
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Auto-generated missing generic tables
CREATE TABLE IF NOT EXISTS starting_formats (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    short_description TEXT,
    long_description TEXT,
    audience_tags JSONB,
    category_tags JSONB,
    recommended_for TEXT,
    sample_output_hint TEXT,
    age_range TEXT,
    visibility_state TEXT,
    show_in_onboarding BOOLEAN DEFAULT false,
    show_in_homeschool BOOLEAN DEFAULT false,
    show_in_teacher_flows BOOLEAN DEFAULT false,
    featured BOOLEAN DEFAULT false,
    sort_order INT DEFAULT 0,
    icon TEXT
);

CREATE TABLE IF NOT EXISTS creator_flows (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    short_description TEXT,
    best_for TEXT,
    output_hint TEXT,
    related_formats JSONB,
    visibility_state TEXT,
    show_in_onboarding BOOLEAN DEFAULT false,
    featured BOOLEAN DEFAULT false,
    sort_order INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS story_goals (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    short_description TEXT,
    category TEXT,
    tags JSONB,
    related_formats JSONB,
    related_creator_flows JSONB,
    importance INT DEFAULT 0,
    visibility_state TEXT,
    show_in_wizard BOOLEAN DEFAULT false,
    show_in_homeschool BOOLEAN DEFAULT false,
    show_in_teacher_flows BOOLEAN DEFAULT false,
    featured BOOLEAN DEFAULT false,
    sort_order INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS usage_modes (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    label TEXT,
    "shortDescription" TEXT,
    "generationBehaviorHint" TEXT,
    "safetyNotes" TEXT,
    "visibleInWizard" BOOLEAN DEFAULT false,
    "sortOrder" INT DEFAULT 0,
    status TEXT
);

CREATE TABLE IF NOT EXISTS personas (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    "displayName" TEXT,
    "shortDescription" TEXT,
    "longDescription" TEXT,
    "personaType" TEXT,
    "roleDefaults" TEXT,
    "ageGroup" TEXT,
    audience_tags JSONB,
    language_tags JSONB,
    "stylePreference" TEXT,
    "visualSummary" TEXT,
    "generationSafeDescription" TEXT,
    "usageMode" TEXT,
    "referenceImageId" TEXT,
    "referenceImageStatus" TEXT,
    "recurringCharacter" TEXT,
    "visibilityScope" TEXT,
    "consentStatus" TEXT,
    "moderationStatus" TEXT,
    "approvedForGeneration" TEXT,
    sort_order INT DEFAULT 0,
    status TEXT
);

CREATE TABLE IF NOT EXISTS styles (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    "shortDescription" TEXT,
    "longDescription" TEXT,
    "visualMood" TEXT,
    "audienceTags" TEXT,
    "useCaseTags" TEXT,
    "styleFamily" TEXT,
    "recommendationTags" TEXT,
    "visibleInStudio" BOOLEAN DEFAULT false,
    "visibleInHomeschool" BOOLEAN DEFAULT false,
    "visibleInTeacherFlow" BOOLEAN DEFAULT false,
    "visibilityState" TEXT,
    featured BOOLEAN DEFAULT false,
    "sortOrder" INT DEFAULT 0,
    "internalTestingOnly" BOOLEAN DEFAULT false,
    "artworkReference" TEXT
);

CREATE TABLE IF NOT EXISTS prompt_templates (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    "workflowType" TEXT,
    "formatMappings" JSONB,
    "creatorFlowMappings" JSONB,
    "styleModifiers" JSONB,
    "educationalMode" TEXT,
    "bilingualHandlingHint" TEXT,
    "personaConsistencyHint" TEXT,
    status TEXT,
    "visibleInAdmin" BOOLEAN DEFAULT false,
    "internalTestingOnly" BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS languages (
    id VARCHAR(255) PRIMARY KEY,
    code TEXT,
    slug TEXT,
    "displayName" TEXT,
    "nativeName" TEXT,
    direction TEXT,
    status TEXT,
    "visibleInStudio" BOOLEAN DEFAULT false,
    "visibleInKidStory" BOOLEAN DEFAULT false,
    "visibleInComicStudio" BOOLEAN DEFAULT false,
    "visibleInTeacherFlow" BOOLEAN DEFAULT false,
    "visibleInHomeschool" BOOLEAN DEFAULT false,
    "supportsBilingual" BOOLEAN DEFAULT false,
    "supportsNarration" BOOLEAN DEFAULT false,
    "supportsTranslation" BOOLEAN DEFAULT false,
    "internalTestingOnly" BOOLEAN DEFAULT false,
    "educationalNotes" TEXT,
    "sortOrder" INT DEFAULT 0,
    featured BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS glossary_entries (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    "sourceTerm" TEXT,
    "preferredTranslation" TEXT,
    "sourceLanguageCode" TEXT,
    "targetLanguageCode" TEXT,
    "termType" TEXT,
    "preserveTerm" BOOLEAN DEFAULT false,
    "scopeType" TEXT,
    "internalTestingOnly" BOOLEAN DEFAULT false,
    status TEXT,
    "sortOrder" INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS translation_workflows (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    "workflowType" TEXT,
    "eligibleSourceLanguages" JSONB,
    "eligibleTargetLanguages" JSONB,
    "glossarySupport" TEXT,
    "protectedTermSupport" TEXT,
    "bilingualOutputSupport" TEXT,
    "narrationCompatibility" TEXT,
    status TEXT,
    "internalTestingOnly" BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS voices (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    "displayName" TEXT,
    "providerId" TEXT,
    "modelId" TEXT,
    "languageCodes" JSONB,
    "primaryLanguageCode" TEXT,
    "accentLabel" TEXT,
    "toneLabel" TEXT,
    "ageDescriptor" TEXT,
    "narratorSuitability" TEXT,
    "childSafe" TEXT,
    "classroomSafe" TEXT,
    "supportsBilingualWorkflows" BOOLEAN DEFAULT false,
    "visibleInStudio" BOOLEAN DEFAULT false,
    "visibleInKidStory" BOOLEAN DEFAULT false,
    "visibleInComicStudio" BOOLEAN DEFAULT false,
    "visibleInTeacherFlow" BOOLEAN DEFAULT false,
    "visibleInHomeschool" BOOLEAN DEFAULT false,
    "internalTestingOnly" BOOLEAN DEFAULT false,
    status TEXT,
    featured BOOLEAN DEFAULT false,
    "sortOrder" INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS soundtrack_items (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    category TEXT,
    mood TEXT,
    "educationalSuitability" TEXT,
    "familySuitability" TEXT,
    "classroomSuitability" TEXT,
    "languageNeutral" TEXT,
    status TEXT,
    "internalTestingOnly" BOOLEAN DEFAULT false,
    "sortOrder" INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS narration_workflows (
    id VARCHAR(255) PRIMARY KEY,
    slug TEXT,
    title TEXT,
    "workflowType" TEXT,
    "eligibleLanguages" JSONB,
    "eligibleVoices" JSONB,
    "soundtrackSupport" TEXT,
    "bilingualCompatibility" TEXT,
    "exportCompatibility" TEXT,
    status TEXT,
    "internalTestingOnly" BOOLEAN DEFAULT false
);

