-- Enable UUID generation extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE (Isolates multi-tenant data safely)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. CHARACTER VAULT TABLE (Stores reusable heroes, sidekicks, and villains)
CREATE TABLE IF NOT EXISTS character_vault (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    character_name VARCHAR(100) NOT NULL,
    role_type VARCHAR(50) NOT NULL, -- 'Hero', 'Co-Star', 'Villain'
    description TEXT,
    image_url TEXT,                 -- Secure path pointing to Google Cloud Storage or base64 data URL
    spatial_vectors JSONB,          -- For structural Gemini reference prompts
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. PROJECTS TABLE (Tracks books/comics generated by creators)
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    language VARCHAR(50) NOT NULL,
    current_page INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. PROJECT CASTING JUNCTION (Links vault characters into specific book issues)
CREATE TABLE IF NOT EXISTS project_casting (
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    character_id UUID REFERENCES character_vault(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, character_id)
);

-- Create performance indexes for rapid fetching
CREATE INDEX IF NOT EXISTS idx_character_vault_user ON character_vault(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);
